[package]
name = "prompt-executor"
version.workspace = true
edition.workspace = true

[dependencies]
anthropic-client = { workspace = true }
llm = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
llm = { workspace = true }
tokio = { workspace = true }
