[package]
name = "openai-client"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = "0.1"
base64 = { workspace = true }
dirs = { workspace = true }
futures = { workspace = true }
llm = { workspace = true }
reqwest = { workspace = true, features = ["stream"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
