[package]
name = "drua-tool-caching"
version.workspace = true
edition.workspace = true

[dependencies]
es-entity = { workspace = true }
regex = "1"
rmcp = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.9"
sqlx = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
