//! Typed wire shapes for every sandbox tool, shared between the
//! sandbox tool server (`images/sandbox/server`) and the in-tree HTTP
//! client (`InstanceClient::execute_*`). Same JSON the server has
//! always accepted — the types just make the contract explicit:
//!
//! - `#[serde(deny_unknown_fields)]` turns caller-side typos (e.g.
//!   `timeoutMs`) into a clear deserialization error rather than a
//!   silently-ignored field.
//! - `#[derive(JsonSchema)]` lets `core::toolset::top_level::schema_for`
//!   build the model-facing JSON Schema directly from these structs,
//!   so the typed Rust contract, the server's input parser, and the
//!   TypeScript signatures generated by `compose_types` all share one
//!   source of truth.

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use thiserror::Error;

// ───────────────────────── bash ─────────────────────────

/// Typed input for the `bash` tool.
#[derive(Debug, Clone, Default, Deserialize, Serialize, JsonSchema, PartialEq, Eq)]
#[serde(rename_all = "snake_case", default, deny_unknown_fields)]
pub struct BashCommandInput {
    /// The bash command to run. Required unless `restart` is true.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,

    /// If true, reset the persistent bash session.
    #[serde(skip_serializing_if = "std::ops::Not::not")]
    pub restart: bool,

    /// Maximum wall-clock time for this command in milliseconds.
    /// Defaults to 120000. Use this for long-running builds or tests
    /// instead of wrapping the command in `timeout(1)`.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[schemars(range(min = 1, max = 10_800_000))]
    pub timeout_ms: Option<u64>,
}

impl BashCommandInput {
    pub const DEFAULT_TIMEOUT_MS: u64 = 120_000;
    pub const MAX_TIMEOUT_MS: u64 = 10_800_000;

    pub fn validated_timeout_ms(&self) -> Result<u64, BashInputError> {
        match self.timeout_ms {
            None => Ok(Self::DEFAULT_TIMEOUT_MS),
            Some(0) => Err(BashInputError::TimeoutZero),
            Some(t) if t > Self::MAX_TIMEOUT_MS => Err(BashInputError::TimeoutTooLarge(t)),
            Some(t) => Ok(t),
        }
    }
}

/// Typed response for the `bash` tool with stdout and stderr kept separate.
#[derive(Debug, Clone, Deserialize, Serialize, JsonSchema, PartialEq, Eq)]
pub struct BashCommandOutput {
    pub stdout: String,
    pub stderr: String,
    pub exit_code: i32,
    pub duration_ms: u64,
}

#[derive(Debug, Error)]
pub enum BashInputError {
    #[error("'timeout_ms' must be greater than 0")]
    TimeoutZero,
    #[error("'timeout_ms' must be at most {max} milliseconds (got {0})", max = BashCommandInput::MAX_TIMEOUT_MS)]
    TimeoutTooLarge(u64),
    #[error("'command' field is required (or set 'restart': true)")]
    MissingCommand,
}

// ───────────────────────── glob ─────────────────────────

/// Typed input for the `Glob` tool.
#[derive(Debug, Clone, Deserialize, Serialize, JsonSchema, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct GlobInput {
    /// Glob pattern to match files (e.g. `**/*.rs`, `src/**/*.ts`).
    pub pattern: String,

    /// Directory to search in. Defaults to workspace root, or use
    /// `space:<slug>/...` to read from a mounted space.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
}

// ───────────────────────── move / delete ─────────────────────────

/// Typed input for the `Move` tool.
#[derive(Debug, Clone, Deserialize, Serialize, JsonSchema, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct MoveInput {
    pub from: String,
    pub to: String,
}

/// Typed input for the `Delete` tool.
#[derive(Debug, Clone, Deserialize, Serialize, JsonSchema, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct DeleteInput {
    pub path: String,
}

// ───────────────────────── grep ─────────────────────────

#[derive(Debug, Clone, Copy, Default, Deserialize, Serialize, JsonSchema, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum GrepOutputMode {
    #[default]
    FilesWithMatches,
    Content,
    Count,
}

/// Typed input for the `Grep` tool. Field names with leading dashes
/// (`-i`, `-n`, `-A`, `-B`, `-C`) preserve the rg-style flag spelling
/// the model has been trained on.
#[derive(Debug, Clone, Default, Deserialize, Serialize, JsonSchema, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct GrepInput {
    /// Regular expression pattern to search for in file contents.
    pub pattern: String,

    /// File or directory to search in. Defaults to workspace root, or
    /// use `space:<slug>/...` to read from a mounted space.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,

    /// Glob pattern to filter files (e.g. `*.rs`, `**/*.{ts,tsx}`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub glob: Option<String>,

    /// File type to search (e.g. `rust`, `py`, `js`).
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub type_: Option<String>,

    /// Output mode. Default: `files_with_matches`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_mode: Option<GrepOutputMode>,

    /// Case insensitive search.
    #[serde(rename = "-i", default, skip_serializing_if = "std::ops::Not::not")]
    pub case_insensitive: bool,

    /// Show line numbers (only with `output_mode = "content"`).
    /// Default: true.
    #[serde(rename = "-n", default, skip_serializing_if = "Option::is_none")]
    pub line_numbers: Option<bool>,

    /// Number of lines to show after each match.
    #[serde(rename = "-A", default, skip_serializing_if = "Option::is_none")]
    pub after_context: Option<u64>,

    /// Number of lines to show before each match.
    #[serde(rename = "-B", default, skip_serializing_if = "Option::is_none")]
    pub before_context: Option<u64>,

    /// Number of context lines before and after each match.
    #[serde(rename = "-C", default, skip_serializing_if = "Option::is_none")]
    pub context: Option<u64>,

    /// Cap output to first N lines.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub head_limit: Option<u64>,

    /// Enable multiline mode where `.` matches newlines.
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub multiline: bool,
}

// ───────────────────────── text editor ─────────────────────────

/// Sub-commands for the `str_replace_based_edit_tool` tool.
#[derive(Debug, Clone, Copy, Deserialize, Serialize, JsonSchema, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum TextEditorCommand {
    View,
    Create,
    StrReplace,
    Insert,
}

/// Typed input for the `str_replace_based_edit_tool` tool — Anthropic-
/// compatible editor with four sub-commands. Modelled as a flat struct
/// with all per-command fields optional so the JSON Schema is a single
/// `type: "object"` (Anthropic / MCP can't currently consume a `oneOf`
/// at the root of a tool's input schema). [`Self::resolve`] enforces
/// the per-command required fields after deserialization.
#[derive(Debug, Clone, Deserialize, Serialize, JsonSchema, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct TextEditorInput {
    /// Which editor operation to perform.
    pub command: TextEditorCommand,

    /// In-sandbox absolute path, or `space:<slug>/...` for a mounted
    /// space (view-only).
    pub path: String,

    /// `[start, end]` line range for `view`. `-1` for end means EOF.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub view_range: Option<[i64; 2]>,

    /// Full file contents for `create`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_text: Option<String>,

    /// Substring to replace for `str_replace`. Must match the file
    /// byte-for-byte and appear exactly once. `view` the file first if
    /// you don't have its current content in context.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub old_str: Option<String>,

    /// Replacement text for `str_replace`, or text to insert for
    /// `insert`. `insert_text` is accepted as a legacy alias.
    #[serde(
        default,
        alias = "insert_text",
        skip_serializing_if = "Option::is_none"
    )]
    pub new_str: Option<String>,

    /// Line number after which to insert text for `insert`.
    /// `0` = beginning of file.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub insert_line: Option<u64>,
}

impl TextEditorInput {
    /// `view` is read-only; everything else mutates state.
    pub fn is_mutating(&self) -> bool {
        !matches!(self.command, TextEditorCommand::View)
    }

    /// Validate per-command required fields and project the flat
    /// struct into a typed variant.
    pub fn resolve(self) -> Result<TextEditorAction, TextEditorInputError> {
        match self.command {
            TextEditorCommand::View => Ok(TextEditorAction::View {
                path: self.path,
                view_range: self.view_range,
            }),
            TextEditorCommand::Create => {
                let file_text = self.file_text.ok_or(TextEditorInputError::MissingField {
                    command: "create",
                    field: "file_text",
                })?;
                Ok(TextEditorAction::Create {
                    path: self.path,
                    file_text,
                })
            }
            TextEditorCommand::StrReplace => {
                let old_str = self.old_str.ok_or(TextEditorInputError::MissingField {
                    command: "str_replace",
                    field: "old_str",
                })?;
                let new_str = self.new_str.ok_or(TextEditorInputError::MissingField {
                    command: "str_replace",
                    field: "new_str",
                })?;
                Ok(TextEditorAction::StrReplace {
                    path: self.path,
                    old_str,
                    new_str,
                })
            }
            TextEditorCommand::Insert => {
                let insert_line = self.insert_line.ok_or(TextEditorInputError::MissingField {
                    command: "insert",
                    field: "insert_line",
                })?;
                let new_str = self.new_str.ok_or(TextEditorInputError::MissingField {
                    command: "insert",
                    field: "new_str",
                })?;
                Ok(TextEditorAction::Insert {
                    path: self.path,
                    insert_line,
                    new_str,
                })
            }
        }
    }
}

/// Resolved per-command shape, produced by [`TextEditorInput::resolve`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TextEditorAction {
    View {
        path: String,
        view_range: Option<[i64; 2]>,
    },
    Create {
        path: String,
        file_text: String,
    },
    StrReplace {
        path: String,
        old_str: String,
        new_str: String,
    },
    Insert {
        path: String,
        insert_line: u64,
        new_str: String,
    },
}

#[derive(Debug, Error)]
pub enum TextEditorInputError {
    #[error("'{field}' is required for command '{command}'")]
    MissingField {
        command: &'static str,
        field: &'static str,
    },
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── bash ──

    #[test]
    fn bash_roundtrip_minimal_input() {
        let input = BashCommandInput {
            command: Some("ls".to_string()),
            ..Default::default()
        };
        let json = serde_json::to_value(&input).unwrap();
        assert_eq!(json, serde_json::json!({"command": "ls"}));
        let back: BashCommandInput = serde_json::from_value(json).unwrap();
        assert_eq!(back, input);
    }

    #[test]
    fn bash_roundtrip_full_input() {
        let input = BashCommandInput {
            command: Some("make build".to_string()),
            restart: false,
            timeout_ms: Some(60_000),
        };
        let json = serde_json::to_value(&input).unwrap();
        assert_eq!(
            json,
            serde_json::json!({"command": "make build", "timeout_ms": 60_000})
        );
        let back: BashCommandInput = serde_json::from_value(json).unwrap();
        assert_eq!(back, input);
    }

    #[test]
    fn bash_roundtrip_restart() {
        let input = BashCommandInput {
            restart: true,
            ..Default::default()
        };
        let json = serde_json::to_value(&input).unwrap();
        assert_eq!(json, serde_json::json!({"restart": true}));
    }

    #[test]
    fn bash_empty_object_deserializes_to_default() {
        let input: BashCommandInput = serde_json::from_value(serde_json::json!({})).unwrap();
        assert_eq!(input, BashCommandInput::default());
    }

    #[test]
    fn bash_unknown_field_is_rejected() {
        let err = serde_json::from_value::<BashCommandInput>(
            serde_json::json!({"command": "ls", "timeoutMs": 1000}),
        )
        .expect_err("camelCase typo should be rejected");
        assert!(
            err.to_string().contains("timeoutMs") || err.to_string().contains("unknown field"),
            "expected unknown-field error, got: {err}"
        );
    }

    #[test]
    fn bash_timeout_validation() {
        let none = BashCommandInput::default();
        assert_eq!(
            none.validated_timeout_ms().unwrap(),
            BashCommandInput::DEFAULT_TIMEOUT_MS
        );

        let ok = BashCommandInput {
            timeout_ms: Some(2500),
            ..Default::default()
        };
        assert_eq!(ok.validated_timeout_ms().unwrap(), 2500);

        let zero = BashCommandInput {
            timeout_ms: Some(0),
            ..Default::default()
        };
        assert!(matches!(
            zero.validated_timeout_ms(),
            Err(BashInputError::TimeoutZero)
        ));

        let too_large = BashCommandInput {
            timeout_ms: Some(BashCommandInput::MAX_TIMEOUT_MS + 1),
            ..Default::default()
        };
        assert!(matches!(
            too_large.validated_timeout_ms(),
            Err(BashInputError::TimeoutTooLarge(_))
        ));
    }

    #[test]
    fn bash_output_roundtrip() {
        for case in [
            BashCommandOutput {
                stdout: "hello\n".to_string(),
                stderr: String::new(),
                exit_code: 0,
                duration_ms: 12,
            },
            BashCommandOutput {
                stdout: String::new(),
                stderr: "oops\n".to_string(),
                exit_code: 1,
                duration_ms: 4,
            },
        ] {
            let json = serde_json::to_value(&case).unwrap();
            let back: BashCommandOutput = serde_json::from_value(json).unwrap();
            assert_eq!(back, case);
        }
    }

    #[test]
    fn bash_input_rejects_string_timeout_ms() {
        let err = serde_json::from_value::<BashCommandInput>(
            serde_json::json!({"command": "ls", "timeout_ms": "1000"}),
        )
        .expect_err("string timeout_ms should be rejected at deser");
        assert!(
            err.to_string().contains("integer") || err.to_string().contains("u64"),
            "expected type error, got: {err}"
        );
    }

    // ── glob ──

    #[test]
    fn glob_roundtrip() {
        let input = GlobInput {
            pattern: "**/*.rs".to_string(),
            path: Some("src".to_string()),
        };
        let json = serde_json::to_value(&input).unwrap();
        assert_eq!(
            json,
            serde_json::json!({"pattern": "**/*.rs", "path": "src"})
        );
        let back: GlobInput = serde_json::from_value(json).unwrap();
        assert_eq!(back, input);
    }

    #[test]
    fn glob_unknown_field_is_rejected() {
        let err = serde_json::from_value::<GlobInput>(
            serde_json::json!({"pattern": "*.rs", "Pattern": "oops"}),
        )
        .expect_err("typo should be rejected");
        assert!(err.to_string().contains("unknown field"));
    }

    // ── move / delete ──

    #[test]
    fn move_roundtrip() {
        let input = MoveInput {
            from: "a.txt".to_string(),
            to: "b.txt".to_string(),
        };
        let json = serde_json::to_value(&input).unwrap();
        assert_eq!(json, serde_json::json!({"from": "a.txt", "to": "b.txt"}));
        let back: MoveInput = serde_json::from_value(json).unwrap();
        assert_eq!(back, input);
    }

    #[test]
    fn delete_roundtrip() {
        let input = DeleteInput {
            path: "x.txt".to_string(),
        };
        let json = serde_json::to_value(&input).unwrap();
        assert_eq!(json, serde_json::json!({"path": "x.txt"}));
        let back: DeleteInput = serde_json::from_value(json).unwrap();
        assert_eq!(back, input);
    }

    // ── grep ──

    #[test]
    fn grep_roundtrip_minimal() {
        let input = GrepInput {
            pattern: "fn ".to_string(),
            ..Default::default()
        };
        let json = serde_json::to_value(&input).unwrap();
        assert_eq!(json, serde_json::json!({"pattern": "fn "}));
        let back: GrepInput = serde_json::from_value(json).unwrap();
        assert_eq!(back, input);
    }

    #[test]
    fn grep_roundtrip_with_dashed_flags() {
        let input = GrepInput {
            pattern: "TODO".to_string(),
            case_insensitive: true,
            after_context: Some(3),
            before_context: Some(1),
            context: Some(5),
            line_numbers: Some(true),
            type_: Some("rust".to_string()),
            output_mode: Some(GrepOutputMode::Content),
            ..Default::default()
        };
        let json = serde_json::to_value(&input).unwrap();
        let obj = json.as_object().unwrap();
        assert_eq!(obj.get("-i").unwrap(), &serde_json::Value::Bool(true));
        assert_eq!(obj.get("-A").unwrap(), &serde_json::json!(3));
        assert_eq!(obj.get("-B").unwrap(), &serde_json::json!(1));
        assert_eq!(obj.get("-C").unwrap(), &serde_json::json!(5));
        assert_eq!(obj.get("-n").unwrap(), &serde_json::Value::Bool(true));
        assert_eq!(
            obj.get("output_mode").unwrap(),
            &serde_json::json!("content")
        );
        let back: GrepInput = serde_json::from_value(json).unwrap();
        assert_eq!(back, input);
    }

    #[test]
    fn grep_unknown_field_rejected() {
        let err = serde_json::from_value::<GrepInput>(serde_json::json!({
            "pattern": "x",
            "headLimit": 5,  // camelCase typo
        }))
        .expect_err("camelCase typo should be rejected");
        assert!(err.to_string().contains("unknown field"));
    }

    // ── text editor ──

    #[test]
    fn text_editor_view_roundtrip() {
        let input: TextEditorInput = serde_json::from_value(serde_json::json!({
            "command": "view",
            "path": "/tmp/x",
            "view_range": [1, -1]
        }))
        .unwrap();
        assert_eq!(input.command, TextEditorCommand::View);
        assert_eq!(input.path, "/tmp/x");
        assert_eq!(input.view_range, Some([1, -1]));
        match input.clone().resolve().unwrap() {
            TextEditorAction::View { path, view_range } => {
                assert_eq!(path, "/tmp/x");
                assert_eq!(view_range, Some([1, -1]));
            }
            other => panic!("expected View, got {other:?}"),
        }
    }

    #[test]
    fn text_editor_create_resolve() {
        let input: TextEditorInput = serde_json::from_value(serde_json::json!({
            "command": "create",
            "path": "/tmp/x",
            "file_text": "hello"
        }))
        .unwrap();
        match input.resolve().unwrap() {
            TextEditorAction::Create { path, file_text } => {
                assert_eq!(path, "/tmp/x");
                assert_eq!(file_text, "hello");
            }
            other => panic!("expected Create, got {other:?}"),
        }
    }

    #[test]
    fn text_editor_create_missing_file_text() {
        let input: TextEditorInput = serde_json::from_value(serde_json::json!({
            "command": "create",
            "path": "/tmp/x"
        }))
        .unwrap();
        let err = input.resolve().expect_err("missing file_text");
        assert!(matches!(
            err,
            TextEditorInputError::MissingField {
                command: "create",
                field: "file_text"
            }
        ));
    }

    #[test]
    fn text_editor_str_replace_resolve() {
        let input: TextEditorInput = serde_json::from_value(serde_json::json!({
            "command": "str_replace",
            "path": "/tmp/x",
            "old_str": "a",
            "new_str": "b"
        }))
        .unwrap();
        match input.resolve().unwrap() {
            TextEditorAction::StrReplace {
                path,
                old_str,
                new_str,
            } => {
                assert_eq!(path, "/tmp/x");
                assert_eq!(old_str, "a");
                assert_eq!(new_str, "b");
            }
            other => panic!("expected StrReplace, got {other:?}"),
        }
    }

    #[test]
    fn text_editor_insert_resolve_with_alias() {
        let input: TextEditorInput = serde_json::from_value(serde_json::json!({
            "command": "insert",
            "path": "/tmp/x",
            "insert_line": 5,
            "insert_text": "// added"
        }))
        .unwrap();
        match input.resolve().unwrap() {
            TextEditorAction::Insert {
                path,
                insert_line,
                new_str,
            } => {
                assert_eq!(path, "/tmp/x");
                assert_eq!(insert_line, 5);
                assert_eq!(new_str, "// added");
            }
            other => panic!("expected Insert, got {other:?}"),
        }
    }

    #[test]
    fn text_editor_unknown_command_rejected() {
        let err = serde_json::from_value::<TextEditorInput>(serde_json::json!({
            "command": "delete",
            "path": "/tmp/x"
        }))
        .expect_err("unknown command should be rejected");
        assert!(
            err.to_string().contains("unknown variant") || err.to_string().contains("delete"),
            "got: {err}"
        );
    }

    #[test]
    fn text_editor_unknown_field_rejected() {
        let err = serde_json::from_value::<TextEditorInput>(serde_json::json!({
            "command": "view",
            "path": "/tmp/x",
            "viewRange": [1, 2]
        }))
        .expect_err("camelCase typo should be rejected");
        assert!(err.to_string().contains("unknown field"));
    }

    #[test]
    fn text_editor_is_mutating() {
        let view = TextEditorInput {
            command: TextEditorCommand::View,
            path: "x".to_string(),
            view_range: None,
            file_text: None,
            old_str: None,
            new_str: None,
            insert_line: None,
        };
        assert!(!view.is_mutating());

        let create = TextEditorInput {
            command: TextEditorCommand::Create,
            ..view
        };
        assert!(create.is_mutating());
    }

    #[test]
    fn text_editor_schema_is_object_root() {
        // MCP / Anthropic tool input schemas must be plain `type: "object"`
        // at the root — not `oneOf`. Pin that here so a future refactor to a
        // tagged enum can't silently break the model-facing schema.
        let settings = schemars::gen::SchemaSettings::draft07().with(|s| {
            s.inline_subschemas = true;
            s.meta_schema = None;
        });
        let generator = settings.into_generator();
        let schema = generator.into_root_schema_for::<TextEditorInput>();
        let value = serde_json::to_value(schema).unwrap();
        assert_eq!(value.get("type").and_then(|t| t.as_str()), Some("object"));
        assert!(
            value.get("oneOf").is_none(),
            "TextEditorInput root schema must not use oneOf"
        );
    }
}
