//! Typed wire shapes for every sandbox tool, shared between the
//! sandbox tool server (`images/sandbox/server`) and the in-tree HTTP
//! client (`InstanceClient::execute_*`). Same JSON the server has
//! always accepted — the types just make the contract explicit:
//!
//! - `#[serde(deny_unknown_fields)]` turns caller-side typos (e.g.
//!   `timeoutMs`) into a clear deserialization error rather than a
//!   silently-ignored field.
//! - `#[derive(JsonSchema)]` lets `core::toolset::top_level::schema_for`
//!   build the model-facing JSON Schema directly from these structs,
//!   so the typed Rust contract, the server's input parser, and the
//!   TypeScript signatures generated by `compose_types` all share one
//!   source of truth.

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use thiserror::Error;

// ───────────────────────── bash ─────────────────────────

/// Typed input for the `bash` tool.
#[derive(Debug, Clone, Default, Deserialize, Serialize, JsonSchema, PartialEq, Eq)]
#[serde(rename_all = "snake_case", default, deny_unknown_fields)]
pub struct BashCommandInput {
    /// The bash command to run. Required unless `restart` is true.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,

    /// If true, reset the persistent bash session.
    #[serde(skip_serializing_if = "std::ops::Not::not")]
    pub restart: bool,

    /// Maximum wall-clock time for this command in milliseconds.
    /// Defaults to 120000. Use this for long-running builds or tests
    /// instead of wrapping the command in `timeout(1)`.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[schemars(range(min = 1, max = 10_800_000))]
    pub timeout_ms: Option<u64>,
}

impl BashCommandInput {
    pub const DEFAULT_TIMEOUT_MS: u64 = 120_000;
    pub const MAX_TIMEOUT_MS: u64 = 10_800_000;

    pub fn validated_timeout_ms(&self) -> Result<u64, BashInputError> {
        match self.timeout_ms {
            None => Ok(Self::DEFAULT_TIMEOUT_MS),
            Some(0) => Err(BashInputError::TimeoutZero),
            Some(t) if t > Self::MAX_TIMEOUT_MS => Err(BashInputError::TimeoutTooLarge(t)),
            Some(t) => Ok(t),
        }
    }
}

/// Typed response for the `bash` tool. Same wire shape as the generic
/// `/execute` envelope — this is a renamed alias on the wire.
#[derive(Debug, Clone, Deserialize, Serialize, JsonSchema, PartialEq, Eq)]
pub struct BashCommandOutput {
    pub output: String,
    pub is_error: bool,
}

#[derive(Debug, Error)]
pub enum BashInputError {
    #[error("'timeout_ms' must be greater than 0")]
    TimeoutZero,
    #[error("'timeout_ms' must be at most {max} milliseconds (got {0})", max = BashCommandInput::MAX_TIMEOUT_MS)]
    TimeoutTooLarge(u64),
    #[error("'command' field is required (or set 'restart': true)")]
    MissingCommand,
}

// ───────────────────────── glob ─────────────────────────

/// Typed input for the `Glob` tool.
#[derive(Debug, Clone, Deserialize, Serialize, JsonSchema, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct GlobInput {
    /// Glob pattern to match files (e.g. `**/*.rs`, `src/**/*.ts`).
    pub pattern: String,

    /// Directory to search in. Defaults to workspace root, or use
    /// `space:<slug>/...` to read from a mounted space.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
}

// ───────────────────────── move / delete ─────────────────────────

/// Typed input for the `Move` tool.
#[derive(Debug, Clone, Deserialize, Serialize, JsonSchema, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct MoveInput {
    pub from: String,
    pub to: String,
}

/// Typed input for the `Delete` tool.
#[derive(Debug, Clone, Deserialize, Serialize, JsonSchema, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct DeleteInput {
    pub path: String,
}

// ───────────────────────── grep ─────────────────────────

#[derive(Debug, Clone, Copy, Default, Deserialize, Serialize, JsonSchema, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum GrepOutputMode {
    #[default]
    FilesWithMatches,
    Content,
    Count,
}

/// Typed input for the `Grep` tool. Field names with leading dashes
/// (`-i`, `-n`, `-A`, `-B`, `-C`) preserve the rg-style flag spelling
/// the model has been trained on.
#[derive(Debug, Clone, Default, Deserialize, Serialize, JsonSchema, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct GrepInput {
    /// Regular expression pattern to search for in file contents.
    pub pattern: String,

    /// File or directory to search in. Defaults to workspace root, or
    /// use `space:<slug>/...` to read from a mounted space.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,

    /// Glob pattern to filter files (e.g. `*.rs`, `**/*.{ts,tsx}`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub glob: Option<String>,

    /// File type to search (e.g. `rust`, `py`, `js`).
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub type_: Option<String>,

    /// Output mode. Default: `files_with_matches`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_mode: Option<GrepOutputMode>,

    /// Case insensitive search.
    #[serde(rename = "-i", default, skip_serializing_if = "std::ops::Not::not")]
    pub case_insensitive: bool,

    /// Show line numbers (only with `output_mode = "content"`).
    /// Default: true.
    #[serde(rename = "-n", default, skip_serializing_if = "Option::is_none")]
    pub line_numbers: Option<bool>,

    /// Number of lines to show after each match.
    #[serde(rename = "-A", default, skip_serializing_if = "Option::is_none")]
    pub after_context: Option<u64>,

    /// Number of lines to show before each match.
    #[serde(rename = "-B", default, skip_serializing_if = "Option::is_none")]
    pub before_context: Option<u64>,

    /// Number of context lines before and after each match.
    #[serde(rename = "-C", default, skip_serializing_if = "Option::is_none")]
    pub context: Option<u64>,

    /// Cap output to first N lines.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub head_limit: Option<u64>,

    /// Enable multiline mode where `.` matches newlines.
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub multiline: bool,
}

// ───────────────────────── text editor ─────────────────────────

/// Typed input for the `str_replace_based_edit_tool` tool — Anthropic-
/// compatible editor with four sub-commands. `#[serde(tag = "command")]`
/// preserves the existing wire shape (`command` discriminator with the
/// per-variant fields flat at the top level).
#[derive(Debug, Clone, Deserialize, Serialize, JsonSchema, PartialEq, Eq)]
#[serde(tag = "command", rename_all = "snake_case", deny_unknown_fields)]
pub enum TextEditorInput {
    /// Read a file or list a directory.
    View {
        /// In-sandbox absolute path, or `space:<slug>/...` for a
        /// mounted space.
        path: String,

        /// `[start, end]` line range. `-1` for end means EOF. Optional.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        view_range: Option<[i64; 2]>,
    },
    /// Write a new file.
    Create {
        path: String,
        /// Full file contents.
        file_text: String,
    },
    /// Replace a unique substring.
    StrReplace {
        path: String,
        /// Substring to replace. Must match the file byte-for-byte and
        /// appear exactly once.
        old_str: String,
        /// Replacement text.
        new_str: String,
    },
    /// Insert text at a line.
    Insert {
        path: String,
        /// Line number after which to insert text. `0` = beginning of
        /// file.
        insert_line: u64,
        /// Text to insert. `insert_text` is accepted as a legacy alias.
        #[serde(alias = "insert_text")]
        new_str: String,
    },
}

impl TextEditorInput {
    /// `view` is read-only; everything else mutates state.
    pub fn is_mutating(&self) -> bool {
        !matches!(self, Self::View { .. })
    }

    pub fn path(&self) -> &str {
        match self {
            Self::View { path, .. }
            | Self::Create { path, .. }
            | Self::StrReplace { path, .. }
            | Self::Insert { path, .. } => path,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── bash ──

    #[test]
    fn bash_roundtrip_minimal_input() {
        let input = BashCommandInput {
            command: Some("ls".to_string()),
            ..Default::default()
        };
        let json = serde_json::to_value(&input).unwrap();
        assert_eq!(json, serde_json::json!({"command": "ls"}));
        let back: BashCommandInput = serde_json::from_value(json).unwrap();
        assert_eq!(back, input);
    }

    #[test]
    fn bash_roundtrip_full_input() {
        let input = BashCommandInput {
            command: Some("make build".to_string()),
            restart: false,
            timeout_ms: Some(60_000),
        };
        let json = serde_json::to_value(&input).unwrap();
        assert_eq!(
            json,
            serde_json::json!({"command": "make build", "timeout_ms": 60_000})
        );
        let back: BashCommandInput = serde_json::from_value(json).unwrap();
        assert_eq!(back, input);
    }

    #[test]
    fn bash_roundtrip_restart() {
        let input = BashCommandInput {
            restart: true,
            ..Default::default()
        };
        let json = serde_json::to_value(&input).unwrap();
        assert_eq!(json, serde_json::json!({"restart": true}));
    }

    #[test]
    fn bash_empty_object_deserializes_to_default() {
        let input: BashCommandInput = serde_json::from_value(serde_json::json!({})).unwrap();
        assert_eq!(input, BashCommandInput::default());
    }

    #[test]
    fn bash_unknown_field_is_rejected() {
        let err = serde_json::from_value::<BashCommandInput>(
            serde_json::json!({"command": "ls", "timeoutMs": 1000}),
        )
        .expect_err("camelCase typo should be rejected");
        assert!(
            err.to_string().contains("timeoutMs") || err.to_string().contains("unknown field"),
            "expected unknown-field error, got: {err}"
        );
    }

    #[test]
    fn bash_timeout_validation() {
        let none = BashCommandInput::default();
        assert_eq!(
            none.validated_timeout_ms().unwrap(),
            BashCommandInput::DEFAULT_TIMEOUT_MS
        );

        let ok = BashCommandInput {
            timeout_ms: Some(2500),
            ..Default::default()
        };
        assert_eq!(ok.validated_timeout_ms().unwrap(), 2500);

        let zero = BashCommandInput {
            timeout_ms: Some(0),
            ..Default::default()
        };
        assert!(matches!(
            zero.validated_timeout_ms(),
            Err(BashInputError::TimeoutZero)
        ));

        let too_large = BashCommandInput {
            timeout_ms: Some(BashCommandInput::MAX_TIMEOUT_MS + 1),
            ..Default::default()
        };
        assert!(matches!(
            too_large.validated_timeout_ms(),
            Err(BashInputError::TimeoutTooLarge(_))
        ));
    }

    #[test]
    fn bash_output_roundtrip() {
        for case in [
            BashCommandOutput {
                output: "hello\n".to_string(),
                is_error: false,
            },
            BashCommandOutput {
                output: "Exit code 1\noops".to_string(),
                is_error: true,
            },
        ] {
            let json = serde_json::to_value(&case).unwrap();
            let back: BashCommandOutput = serde_json::from_value(json).unwrap();
            assert_eq!(back, case);
        }
    }

    #[test]
    fn bash_input_rejects_string_timeout_ms() {
        let err = serde_json::from_value::<BashCommandInput>(
            serde_json::json!({"command": "ls", "timeout_ms": "1000"}),
        )
        .expect_err("string timeout_ms should be rejected at deser");
        assert!(
            err.to_string().contains("integer") || err.to_string().contains("u64"),
            "expected type error, got: {err}"
        );
    }

    // ── glob ──

    #[test]
    fn glob_roundtrip() {
        let input = GlobInput {
            pattern: "**/*.rs".to_string(),
            path: Some("src".to_string()),
        };
        let json = serde_json::to_value(&input).unwrap();
        assert_eq!(
            json,
            serde_json::json!({"pattern": "**/*.rs", "path": "src"})
        );
        let back: GlobInput = serde_json::from_value(json).unwrap();
        assert_eq!(back, input);
    }

    #[test]
    fn glob_unknown_field_is_rejected() {
        let err = serde_json::from_value::<GlobInput>(
            serde_json::json!({"pattern": "*.rs", "Pattern": "oops"}),
        )
        .expect_err("typo should be rejected");
        assert!(err.to_string().contains("unknown field"));
    }

    // ── move / delete ──

    #[test]
    fn move_roundtrip() {
        let input = MoveInput {
            from: "a.txt".to_string(),
            to: "b.txt".to_string(),
        };
        let json = serde_json::to_value(&input).unwrap();
        assert_eq!(json, serde_json::json!({"from": "a.txt", "to": "b.txt"}));
        let back: MoveInput = serde_json::from_value(json).unwrap();
        assert_eq!(back, input);
    }

    #[test]
    fn delete_roundtrip() {
        let input = DeleteInput {
            path: "x.txt".to_string(),
        };
        let json = serde_json::to_value(&input).unwrap();
        assert_eq!(json, serde_json::json!({"path": "x.txt"}));
        let back: DeleteInput = serde_json::from_value(json).unwrap();
        assert_eq!(back, input);
    }

    // ── grep ──

    #[test]
    fn grep_roundtrip_minimal() {
        let input = GrepInput {
            pattern: "fn ".to_string(),
            ..Default::default()
        };
        let json = serde_json::to_value(&input).unwrap();
        assert_eq!(json, serde_json::json!({"pattern": "fn "}));
        let back: GrepInput = serde_json::from_value(json).unwrap();
        assert_eq!(back, input);
    }

    #[test]
    fn grep_roundtrip_with_dashed_flags() {
        let input = GrepInput {
            pattern: "TODO".to_string(),
            case_insensitive: true,
            after_context: Some(3),
            before_context: Some(1),
            context: Some(5),
            line_numbers: Some(true),
            type_: Some("rust".to_string()),
            output_mode: Some(GrepOutputMode::Content),
            ..Default::default()
        };
        let json = serde_json::to_value(&input).unwrap();
        let obj = json.as_object().unwrap();
        assert_eq!(obj.get("-i").unwrap(), &serde_json::Value::Bool(true));
        assert_eq!(obj.get("-A").unwrap(), &serde_json::json!(3));
        assert_eq!(obj.get("-B").unwrap(), &serde_json::json!(1));
        assert_eq!(obj.get("-C").unwrap(), &serde_json::json!(5));
        assert_eq!(obj.get("-n").unwrap(), &serde_json::Value::Bool(true));
        assert_eq!(
            obj.get("output_mode").unwrap(),
            &serde_json::json!("content")
        );
        let back: GrepInput = serde_json::from_value(json).unwrap();
        assert_eq!(back, input);
    }

    #[test]
    fn grep_unknown_field_rejected() {
        let err = serde_json::from_value::<GrepInput>(serde_json::json!({
            "pattern": "x",
            "headLimit": 5,  // camelCase typo
        }))
        .expect_err("camelCase typo should be rejected");
        assert!(err.to_string().contains("unknown field"));
    }

    // ── text editor ──

    #[test]
    fn text_editor_view_roundtrip() {
        let input = TextEditorInput::View {
            path: "/tmp/x".to_string(),
            view_range: Some([1, -1]),
        };
        let json = serde_json::to_value(&input).unwrap();
        assert_eq!(
            json,
            serde_json::json!({
                "command": "view",
                "path": "/tmp/x",
                "view_range": [1, -1]
            })
        );
        let back: TextEditorInput = serde_json::from_value(json).unwrap();
        assert_eq!(back, input);
    }

    #[test]
    fn text_editor_create_roundtrip() {
        let input = TextEditorInput::Create {
            path: "/tmp/x".to_string(),
            file_text: "hello".to_string(),
        };
        let json = serde_json::to_value(&input).unwrap();
        assert_eq!(
            json,
            serde_json::json!({
                "command": "create",
                "path": "/tmp/x",
                "file_text": "hello"
            })
        );
        let back: TextEditorInput = serde_json::from_value(json).unwrap();
        assert_eq!(back, input);
    }

    #[test]
    fn text_editor_str_replace_roundtrip() {
        let input = TextEditorInput::StrReplace {
            path: "/tmp/x".to_string(),
            old_str: "a".to_string(),
            new_str: "b".to_string(),
        };
        let json = serde_json::to_value(&input).unwrap();
        assert_eq!(
            json,
            serde_json::json!({
                "command": "str_replace",
                "path": "/tmp/x",
                "old_str": "a",
                "new_str": "b"
            })
        );
        let back: TextEditorInput = serde_json::from_value(json).unwrap();
        assert_eq!(back, input);
    }

    #[test]
    fn text_editor_insert_roundtrip() {
        let input = TextEditorInput::Insert {
            path: "/tmp/x".to_string(),
            insert_line: 5,
            new_str: "// added".to_string(),
        };
        let json = serde_json::to_value(&input).unwrap();
        assert_eq!(
            json,
            serde_json::json!({
                "command": "insert",
                "path": "/tmp/x",
                "insert_line": 5,
                "new_str": "// added"
            })
        );
        let back: TextEditorInput = serde_json::from_value(json).unwrap();
        assert_eq!(back, input);
    }

    #[test]
    fn text_editor_unknown_command_rejected() {
        let err = serde_json::from_value::<TextEditorInput>(serde_json::json!({
            "command": "delete",
            "path": "/tmp/x"
        }))
        .expect_err("unknown command should be rejected");
        assert!(
            err.to_string().contains("unknown variant") || err.to_string().contains("delete"),
            "got: {err}"
        );
    }

    #[test]
    fn text_editor_is_mutating() {
        let view = TextEditorInput::View {
            path: "x".to_string(),
            view_range: None,
        };
        assert!(!view.is_mutating());

        let create = TextEditorInput::Create {
            path: "x".to_string(),
            file_text: "y".to_string(),
        };
        assert!(create.is_mutating());
    }
}
