[package]
name = "sandbox-tool-server"
edition.workspace = true
version.workspace = true

[dependencies]
axum.workspace = true
drua-tracing-utils = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-http = "0.31"
sandbox = { workspace = true }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml = "0.9"
tracing.workspace = true
tracing-opentelemetry = { workspace = true }
uuid.workspace = true

[dev-dependencies]
http = "1"
opentelemetry_sdk = { workspace = true }
tower = { version = "0.5", features = ["util"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
