{{- if .Values.drua.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "drua.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "drua.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  {{- with .Values.drua.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.drua.ingress.ingressClassName }}
  ingressClassName: {{ .Values.drua.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.drua.ingress.tls }}
  tls:
    {{- toYaml .Values.drua.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
  - host: {{ .Values.drua.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "drua.fullname" . }}
            port:
              number: {{ .Values.drua.server.service.port }}
{{- end }}
