{{- with .Values.galoyAgents.config.library }}
{{- with .dataDir }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "galoyAgents.fullname" $ }}-library
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "galoyAgents.fullname" $ }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.galoyAgents.config.library.size | default "1Gi" }}
  {{- with $.Values.galoyAgents.config.library.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
