{{- if .Values.drua.postgresMcp.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "drua.postgresMcp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "drua.postgresMcp.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  type: {{ .Values.drua.postgresMcp.service.type }}
  ports:
  - port: {{ .Values.drua.postgresMcp.service.port }}
    targetPort: {{ .Values.drua.postgresMcp.service.port }}
    protocol: TCP
    name: http
  selector:
    app: {{ template "drua.postgresMcp.fullname" . }}
{{- end }}
