{{- if and .Values.sandbox.enabled .Values.sandbox.nixNetrc.enabled .Values.sandbox.nixNetrc.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "galoyAgents.sandbox.nixNetrcSecretName" . }}
  namespace: {{ include "galoyAgents.sandboxNamespace" . }}
  labels:
    app: {{ template "galoyAgents.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
type: Opaque
stringData:
  {{ .Values.sandbox.nixNetrc.secret.key }}: |-
{{ .Values.sandbox.nixNetrc.secret.contents | indent 4 }}
{{- end }}
