{{- if and .Values.sandbox.enabled .Values.sandbox.nixCacheProxy.enabled .Values.sandbox.nixCacheProxy.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "galoyAgents.sandbox.nixCacheProxy.fullname" . }}-cache
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "galoyAgents.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    app.kubernetes.io/component: sandbox-nix-cache-proxy
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sandbox.nixCacheProxy.persistence.size }}
  {{- if .Values.sandbox.nixCacheProxy.persistence.storageClassName }}
  storageClassName: {{ .Values.sandbox.nixCacheProxy.persistence.storageClassName | quote }}
  {{- end }}
{{- end }}
