{{- if and .Values.sandbox.enabled .Values.sandbox.namespace .Values.sandbox.createNamespace }}
{{- if ne .Values.sandbox.namespace .Release.Namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.sandbox.namespace }}
  labels:
    app: {{ template "drua.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
{{- end }}
{{- end }}
