{{- if .Values.galoyAgents.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "galoyAgents.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "galoyAgents.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  {{- if .Values.galoyAgents.secrets.annotations }}
  annotations:
{{ toYaml .Values.galoyAgents.secrets.annotations | indent 4 }}
  {{- end }}
type: Opaque
data:
  pg-con: {{ .Values.galoyAgents.secrets.pgCon | trim | b64enc | trim }}
  {{- if .Values.galoyAgents.secrets.pgMcpUri }}
  pg-mcp-uri: {{ .Values.galoyAgents.secrets.pgMcpUri | trim | b64enc | trim }}
  {{- end }}
  github-client-secret: {{ .Values.galoyAgents.secrets.githubClientSecret | trim | b64enc | trim }}
  {{- if .Values.galoyAgents.secrets.concourseUsername }}
  concourse-username: {{ .Values.galoyAgents.secrets.concourseUsername | trim | b64enc | trim }}
  {{- end }}
  {{- if .Values.galoyAgents.secrets.concoursePassword }}
  concourse-password: {{ .Values.galoyAgents.secrets.concoursePassword | trim | b64enc | trim }}
  {{- end }}
  {{- if .Values.galoyAgents.secrets.zendutyApiToken }}
  zenduty-api-token: {{ .Values.galoyAgents.secrets.zendutyApiToken | trim | b64enc | trim }}
  {{- end }}
  {{- if .Values.galoyAgents.codeAssistant.gcsCreds }}
  gcs-creds: {{ .Values.galoyAgents.codeAssistant.gcsCreds | trim | b64enc | trim }}
  {{- end }}
  {{- if .Values.galoyAgents.secrets.anthropicApiKey }}
  anthropic-api-key: {{ .Values.galoyAgents.secrets.anthropicApiKey | trim | b64enc | trim }}
  {{- end }}
  {{- if .Values.galoyAgents.secrets.openaiApiKey }}
  openai-api-key: {{ .Values.galoyAgents.secrets.openaiApiKey | trim | b64enc | trim }}
  {{- end }}
  {{- if .Values.galoyAgents.secrets.githubAppWebhookSecret }}
  github-app-webhook-secret: {{ .Values.galoyAgents.secrets.githubAppWebhookSecret | trim | b64enc | trim }}
  {{- end }}
  {{- if .Values.galoyAgents.secrets.concourseWebhookSecret }}
  concourse-webhook-secret: {{ .Values.galoyAgents.secrets.concourseWebhookSecret | trim | b64enc | trim }}
  {{- end }}
  {{- if .Values.galoyAgents.secrets.tunnelInternalSecret }}
  tunnel-internal-secret: {{ .Values.galoyAgents.secrets.tunnelInternalSecret | trim | b64enc | trim }}
  {{- end }}
{{- end }}
