{{- if .Values.drua.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "drua.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "drua.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  {{- if .Values.drua.secrets.annotations }}
  annotations:
{{ toYaml .Values.drua.secrets.annotations | indent 4 }}
  {{- end }}
type: Opaque
data:
  pg-con: {{ .Values.drua.secrets.pgCon | trim | b64enc | trim }}
  {{- if .Values.drua.secrets.pgMcpUri }}
  pg-mcp-uri: {{ .Values.drua.secrets.pgMcpUri | trim | b64enc | trim }}
  {{- end }}
  github-client-secret: {{ .Values.drua.secrets.githubClientSecret | trim | b64enc | trim }}
  {{- if .Values.drua.secrets.concourseUsername }}
  concourse-username: {{ .Values.drua.secrets.concourseUsername | trim | b64enc | trim }}
  {{- end }}
  {{- if .Values.drua.secrets.concoursePassword }}
  concourse-password: {{ .Values.drua.secrets.concoursePassword | trim | b64enc | trim }}
  {{- end }}
  {{- if .Values.drua.codeAssistant.gcsCreds }}
  gcs-creds: {{ .Values.drua.codeAssistant.gcsCreds | trim | b64enc | trim }}
  {{- end }}
  {{- if .Values.drua.secrets.anthropicApiKey }}
  anthropic-api-key: {{ .Values.drua.secrets.anthropicApiKey | trim | b64enc | trim }}
  {{- end }}
{{- end }}
