apiVersion: v1
kind: Service
metadata:
  name: {{ template "drua.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "drua.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  {{- with .Values.drua.server.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.drua.server.service.type }}
  ports:
  - port: {{ .Values.drua.server.service.port }}
    targetPort: server
    protocol: TCP
    name: http
  selector:
    app: {{ template "drua.fullname" . }}
    release: {{ .Release.Name }}
