apiVersion: v1
kind: Service
{{- $serviceAnnotations := dict -}}
{{- with .Values.galoyAgents.server.service.annotations -}}
{{- $serviceAnnotations = . -}}
{{- end -}}
{{- if .Values.galoyAgents.serverTransport.enabled -}}
{{- $_ := set $serviceAnnotations "traefik.ingress.kubernetes.io/service.serverstransport" (printf "%s-%s@kubernetescrd" .Release.Namespace (include "galoyAgents.serverTransport.fullname" .)) -}}
{{- end }}
metadata:
  name: {{ template "galoyAgents.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "galoyAgents.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  {{- with $serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.galoyAgents.server.service.type }}
  ports:
  - port: {{ .Values.galoyAgents.server.service.port }}
    targetPort: server
    protocol: TCP
    name: http
  selector:
    app: {{ template "galoyAgents.fullname" . }}
    release: {{ .Release.Name }}
