[package]
name = "concourse-client"
version.workspace = true
edition.workspace = true

[dependencies]
futures-util = "0.3"
reqwest = { workspace = true, features = ["stream"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = "2"
