[package]
name = "galoy-agents-core"
version.workspace = true
edition.workspace = true

[lib]

[dependencies]
code-assistant-core = { workspace = true }
anyhow = { workspace = true }
async-trait = "0.1"
base64 = "0.22"
concourse-client = { workspace = true }
chrono = { version = "0.4", features = ["clock", "serde"], default-features = false }
derive_builder = "0.20"
es-entity = "0.10"
http = "1"
rand = "0.9"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }
reqwest = { version = "0.13", default-features = false, features = ["rustls"] }
rmcp = { workspace = true }
thiserror = "2.0"
tokio = { version = "1", features = ["rt"] }
tracing = "0.1"
uuid = { version = "1", features = ["serde", "v4", "v7"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
