[package]
name = "drua-core"
version.workspace = true
edition.workspace = true

[features]
graphql = ["es-entity/graphql", "dep:async-graphql"]

[lib]

[dependencies]
async-graphql = { version = "8.0.0-rc.4", optional = true, default-features = false }
anthropic-client = { workspace = true }
code-assistant-core = { workspace = true }
drua-library = { path = "crates/library" }
github-app = { workspace = true }
openai-client = { workspace = true }
anyhow = { workspace = true }
async-trait = "0.1"
base64 = "0.22"
chacha20poly1305 = "0.10"
concourse-client = { workspace = true }
zenduty-client = { workspace = true }
chrono = { version = "0.4", features = ["clock", "serde"], default-features = false }
chrono-tz = "0.10"
cron = "0.15"
derive_builder = "0.20"
es-entity = "0.10"
job = { workspace = true }
obix = { workspace = true }
futures = { workspace = true }
hex = "0.4"
js-engine = { workspace = true }
json-schema-ts = { workspace = true }
http = "1"
llm = { workspace = true }
rand = "0.9"
regex = "1"
schemars = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
sha1 = { workspace = true }
sha2 = "0.10"
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json", "macros"] }
pgvector = { workspace = true }
jsonwebtoken = { version = "9", default-features = false, features = ["use_pem"] }
reqwest = { version = "0.13", default-features = false, features = ["rustls", "json"] }
rmcp = { workspace = true }
thiserror = "2.0"
sandbox = { workspace = true }
tokio = { version = "1", features = ["rt", "io-util", "sync", "time"] }
opentelemetry = { workspace = true }
opentelemetry-http = { workspace = true }
tracing = "0.1"
tracing-opentelemetry = { workspace = true }
uuid = { version = "1", features = ["serde", "v4", "v5", "v7"] }

[dev-dependencies]
async-trait = "0.1"
git2 = { version = "0.20", default-features = false, features = ["vendored-libgit2", "vendored-openssl", "https", "ssh"] }
llm = { workspace = true }
rmcp = { workspace = true }
serde_json = "1.0"
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "test-util"] }
uuid = { version = "1", features = ["serde", "v4", "v5", "v7"] }
