{{- if .Values.kubernetesMcpServer.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "galoyAgents.fullname" . }}-k8s-mcp
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "galoyAgents.fullname" . }}-k8s-mcp
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
{{- end }}
