{{- if and .Values.sandbox.enabled .Values.sandbox.warmPool.enabled }}
apiVersion: extensions.agents.x-k8s.io/v1alpha1
kind: SandboxWarmPool
metadata:
  name: {{ .Values.sandbox.templateName }}-pool
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "galoyAgents.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  sandboxTemplateRef:
    name: {{ .Values.sandbox.templateName }}
  replicas: {{ .Values.sandbox.warmPool.minReady }}
{{- end }}
