#@ load("@ytt:data", "data")
#@ load("fragments.lib.yml",
#@   "nix_flake_cachix_image_config",
#@ )

groups:
- name: galoy-agents
  jobs:
  - check-code
  - test-bats
  - build-edge-image

jobs:
- name: check-code
  serial: true
  plan:
  - get: repo
    trigger: true
  - task: nix-flake-check
    config:
      platform: linux
      image_resource: #@ nix_flake_cachix_image_config()
      inputs:
      - name: repo
      params:
        CACHIX_AUTH_TOKEN: #@ data.values.cachix_auth_token
        CACHIX_CACHE_NAME: #@ data.values.cachix_cache_name
      run:
        path: sh
        args:
          - -exc
          - |
            set -euo pipefail
            cd repo
            cachix use $CACHIX_CACHE_NAME
            nix flake check

- name: test-bats
  serial: true
  plan:
  - get: repo
    trigger: true
    passed: [check-code]
  - task: bats-e2e
    privileged: true
    attempts: 2
    config:
      platform: linux
      image_resource: #@ nix_flake_cachix_image_config()
      inputs:
      - name: repo
      params:
        CACHIX_AUTH_TOKEN: #@ data.values.cachix_auth_token
        CACHIX_CACHE_NAME: #@ data.values.cachix_cache_name
      run:
        path: sh
        args:
          - -exc
          - |
            set -euo pipefail
            cd repo
            cachix use $CACHIX_CACHE_NAME
            nix run .#bats

- name: build-edge-image
  serial: true
  plan:
  - get: repo
    trigger: true
    passed: [test-bats]
  - task: build-image
    config:
      platform: linux
      image_resource: #@ nix_flake_cachix_image_config()
      inputs:
      - name: repo
      outputs:
      - name: image
      params:
        CACHIX_AUTH_TOKEN: #@ data.values.cachix_auth_token
        CACHIX_CACHE_NAME: #@ data.values.cachix_cache_name
      run:
        path: sh
        args:
          - -exc
          - |
            set -euo pipefail
            cd repo
            cachix use $CACHIX_CACHE_NAME
            cachix watch-exec $CACHIX_CACHE_NAME -- nix build .#docker-image
            gunzip -c result > ../image/image.tar
  - put: edge-image
    params:
      image: image/image.tar

resources:
- name: repo
  type: git
  source:
    ignore_paths: ["ci/*[^md]"]
    fetch_tags: true
    uri: #@ data.values.git_uri
    branch: #@ data.values.git_branch
    private_key: #@ data.values.github_private_key
  webhook_token: ((webhook.secret))

- name: edge-image
  type: registry-image
  source:
    tag: edge
    username: #@ data.values.gar_registry_user
    password: #@ data.values.gar_registry_password
    repository: #@ data.values.gar_registry + "/" + data.values.folder_registry_image
