#@data/values
---
git_uri: git@github.com:GaloyMoney/Galoy-agents.git
git_branch: main
github_private_key: ((github.private_key))

gar_registry: us.gcr.io/galoyorg
gar_registry_user: ((gar-creds.username))
gar_registry_password: ((gar-creds.password))

cachix_auth_token: ((cachix-token.token))
cachix_cache_name: galoymoney

folder_registry_image: galoy-agents
