//! Pure-data types describing a workflow's *shape* — what trips it, what
//! it runs. Persisted verbatim inside [`super::entity::WorkflowDefinitionEvent`]
//! and snapshotted on every [`super::run::WorkflowRunEvent::Initialized`],
//! so any change to these types is a wire-format change and must remain
//! backward-compatible.

use serde::{Deserialize, Serialize};

/// How a workflow is triggered.
///
/// MVP supports `Manual` (CLI / MCP) and `Webhook` (HTTP POST). Webhook
/// secrets are auto-generated by the service at create time and persisted
/// as-is on the `Initialized` event — we don't encrypt them yet.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum WorkflowTrigger {
    Manual,
    Webhook {
        /// Provider tag (e.g. `"honeycomb"`). `None` means a generic
        /// shared-token webhook (`Authorization: Bearer …`).
        provider: Option<String>,
        secret: String,
    },
}

/// One step in a workflow definition. MVP only supports `AgentStep`; the
/// `ToolStep` variant is deferred.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum WorkflowStepDef {
    AgentStep {
        name: String,
        skill: String,
        sandbox: Option<String>,
        timeout_seconds: Option<u64>,
    },
}

impl WorkflowStepDef {
    pub fn name(&self) -> &str {
        match self {
            WorkflowStepDef::AgentStep { name, .. } => name,
        }
    }
}
