name: "setup-nix"

description: "Install Nix and configure Cachix."

inputs:
  cachix_auth_token:
    description: "Cachix authentication token."
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - uses: DeterminateSystems/nix-installer-action@v16
    - uses: cachix/cachix-action@v17
      if: inputs.cachix_auth_token != ''
      with:
        name: galoy-agents-github-action
        authToken: ${{ inputs.cachix_auth_token }}
        skipPush: false
