type Mutation {
	"""
	Placeholder — will be replaced with real mutations.
	"""
	ping: String!
	workspaceCreate(input: WorkspaceCreateInput!): WorkspaceCreatePayload!
	workspaceDelete(input: WorkspaceDeleteInput!): WorkspaceDeletePayload!
	workspaceUpdate(input: WorkspaceUpdateInput!): WorkspaceUpdatePayload!
}

type Query {
	"""
	The ID of the currently authenticated user, if any.
	"""
	me: UUID
	ping: String!
	workspace(id: WorkspaceId!): Workspace
	workspaces: [Workspace!]!
}

"""
An ISO 8601 UTC timestamp (e.g., 2024-01-15T09:30:00Z). Always in UTC.
"""
scalar Timestamp

scalar UUID

type Workspace {
	createdAt: Timestamp!
	description: String
	id: WorkspaceId!
	name: String!
}

input WorkspaceCreateInput {
	description: String
	name: String!
}

type WorkspaceCreatePayload {
	workspace: Workspace!
}

input WorkspaceDeleteInput {
	id: WorkspaceId!
}

type WorkspaceDeletePayload {
	workspace: Workspace!
}

scalar WorkspaceId

input WorkspaceUpdateInput {
	description: String
	id: WorkspaceId!
	name: String!
}

type WorkspaceUpdatePayload {
	workspace: Workspace!
}

"""
Directs the executor to include this field or fragment only when the `if` argument is true.
"""
directive @include(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
"""
Directs the executor to skip this field or fragment when the `if` argument is true.
"""
directive @skip(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
schema {
	query: Query
	mutation: Mutation
}
